package cn.besbing.Dao;

import cn.besbing.CommonUtils.MaintainModel.SearchDTO;
import cn.besbing.Entities.CProjTask;
import cn.besbing.Entities.CProjTaskExample;
import java.util.List;

import cn.besbing.Entities.TableTaskFields;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestParam;

public interface CProjTaskMapper {
    List<TableTaskFields> selectForTable(@RequestParam(value = "taskid", required = false) String taskid);

    CProjTask selectByTaskId(@RequestParam(value = "taskid", required = false) String taskid);

    int updateByTaskId(CProjTask record);

    long countByExample(CProjTaskExample example);

    int deleteByExample(CProjTaskExample example);

    int deleteByPrimaryKey(Long seqNum);

    int insert(CProjTask record);

    int insertSelective(CProjTask record);

    List<CProjTask> selectByExample(CProjTaskExample example);

    CProjTask selectByPrimaryKey(Long seqNum);

    int updateByExampleSelective(@Param("record") CProjTask record, @Param("example") CProjTaskExample example);

    int updateByExample(@Param("record") CProjTask record, @Param("example") CProjTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int updateByPrimaryKeySelective(CProjTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int updateByPrimaryKey(CProjTask record);
}