package cn.besbing.Dao;

import cn.besbing.Entities.CProjTask;
import cn.besbing.Entities.CProjTaskExample;
import java.util.List;

import cn.besbing.Entities.TableTaskFields;
import org.apache.ibatis.annotations.Param;

public interface CProjTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    List<TableTaskFields> selectForTable();

    long countByExample(CProjTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int deleteByExample(CProjTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int deleteByPrimaryKey(Long seqNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int insert(CProjTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int insertSelective(CProjTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    List<CProjTask> selectByExample(CProjTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    CProjTask selectByPrimaryKey(Long seqNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") CProjTask record, @Param("example") CProjTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int updateByExample(@Param("record") CProjTask record, @Param("example") CProjTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int updateByPrimaryKeySelective(CProjTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_PROJ_TASK
     *
     * @mbg.generated Thu May 21 19:12:22 CST 2020
     */
    int updateByPrimaryKey(CProjTask record);
}