package cn.besbing.Dao;

import cn.besbing.CommonUtils.MaintainModel.FormatSearchDTO;
import cn.besbing.Entities.Instruments;
import cn.besbing.Entities.InstrumentsExample;
import cn.besbing.Entities.InstrumentsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstrumentsMapper {

    List<InstrumentsWithBLOBs> getAllData(FormatSearchDTO userSearch);
    List<InstrumentsWithBLOBs> getReloadData(String pk);
    List<InstrumentsWithBLOBs> getInstruments(String pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    long countByExample(InstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int deleteByExample(InstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int insert(InstrumentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int insertSelective(InstrumentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    List<InstrumentsWithBLOBs> selectByExampleWithBLOBs(InstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    List<Instruments> selectByExample(InstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    InstrumentsWithBLOBs selectByPrimaryKey(String name);

    List<InstrumentsWithBLOBs> selectAllInstruments();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") InstrumentsWithBLOBs record, @Param("example") InstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") InstrumentsWithBLOBs record, @Param("example") InstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int updateByExample(@Param("record") Instruments record, @Param("example") InstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int updateByPrimaryKeySelective(InstrumentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(InstrumentsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTRUMENTS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    int updateByPrimaryKey(Instruments record);
}