package cn.besbing.Dao;

import cn.besbing.Entities.LimsUsers;
import cn.besbing.Entities.LimsUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LimsUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    long countByExample(LimsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int deleteByExample(LimsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int insert(LimsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int insertSelective(LimsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    List<LimsUsers> selectByExample(LimsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    LimsUsers selectByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") LimsUsers record, @Param("example") LimsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int updateByExample(@Param("record") LimsUsers record, @Param("example") LimsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int updateByPrimaryKeySelective(LimsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIMS_USERS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    int updateByPrimaryKey(LimsUsers record);
}