package cn.besbing.Dao;

import cn.besbing.Entities.SmUser;
import cn.besbing.Entities.SmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    long countByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int deleteByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int deleteByPrimaryKey(String cuserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int insert(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int insertSelective(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    List<SmUser> selectByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    SmUser selectByPrimaryKey(String cuserid);

    SmUser selectUserPasswordByUserCode(String usercode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") SmUser record, @Param("example") SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int updateByExample(@Param("record") SmUser record, @Param("example") SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int updateByPrimaryKeySelective(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Tue Apr 14 11:55:41 CST 2020
     */
    int updateByPrimaryKey(SmUser record);
}