package cn.besbing.Entities;

public class AnalysisKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS.NAME
     *
     * @mbg.generated Mon May 04 16:55:47 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALYSIS.VERSION
     *
     * @mbg.generated Mon May 04 16:55:47 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS.NAME
     *
     * @return the value of ANALYSIS.NAME
     *
     * @mbg.generated Mon May 04 16:55:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS.NAME
     *
     * @param name the value for ANALYSIS.NAME
     *
     * @mbg.generated Mon May 04 16:55:47 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALYSIS.VERSION
     *
     * @return the value of ANALYSIS.VERSION
     *
     * @mbg.generated Mon May 04 16:55:47 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALYSIS.VERSION
     *
     * @param version the value for ANALYSIS.VERSION
     *
     * @mbg.generated Mon May 04 16:55:47 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}