package cn.besbing.Entities;

import java.math.BigDecimal;
import java.util.Date;

public class Instruments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.GROUP_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.DESCRIPTION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String instGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.ON_LINE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String onLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.LOCATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.OPERATOR
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.VENDOR
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String vendor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.SERIAL_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PM_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date pmDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PM_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long pmIntv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PM_EXPIRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date pmExpiration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.CALIB_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date calibDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.CALIB_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long calibIntv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.CALIB_EXPIRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date calibExpiration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.CHANGED_ON
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date changedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.CHANGED_BY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String changedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.REMOVED
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String removed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.EXT_LINK
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String extLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.LINK_LOCATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String linkLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PARAMETER_1_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String parameter1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PARAMETER_1_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String parameter1Value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PARAMETER_2_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String parameter2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PARAMETER_2_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String parameter2Value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.LABSTATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String labstation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.BAUD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String baud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PARITY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String parity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.STOP_BITS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String stopBits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.DATA_BITS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String dataBits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.FLOW_CONTROL
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String flowControl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.INSTRUMENT_CLASS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String instrumentClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.LOW_THRESHOLD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private BigDecimal lowThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.HIGH_THRESHOLD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private BigDecimal highThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.STABILITY_DELTA
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private BigDecimal stabilityDelta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.STABILITY_NUMBER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long stabilityNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PARENT_INSTRUMENT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String parentInstrument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.INST_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String instTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.CALIB_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String calibTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PM_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String pmTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.SERVICE_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String serviceTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.NEEDS_CALIBRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String needsCalibration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.NEEDS_PM
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String needsPm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.IP_ADDRESS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PORT_NUMBER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long portNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.TERM_PATTERN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String termPattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.TIME_OUT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long timeOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.XMIT_PREFIX
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String xmitPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.XMIT_SUFFIX
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String xmitSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.POLLING_TIME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long pollingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.COMM_PORT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String commPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.HOLDS_SAMPLES
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String holdsSamples;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.DATA_PATH
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String dataPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.DISCARD_TIME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long discardTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.FILTER_SCRIPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String filterScript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PARSING_SCRIPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String parsingScript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.POST_ARCHIVE_ACTION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String postArchiveAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.SIZE_LIMIT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long sizeLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.SYNC_PATTERN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String syncPattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.RENAME_EXT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String renameExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.SOURCE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.STEP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.INCLUDE_SUBDIRS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String includeSubdirs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.FTP_USER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String ftpUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.DEBUG
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String debug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.DIRECTORY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String directory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.FTP_MODE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String ftpMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.PASSWORD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.STORE_IN_DB_FILE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String storeInDbFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.DB_FILE_PROMPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String dbFilePrompt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_EQ_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cEqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_MODEL
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_TECH_SPEC
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cTechSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_ACCURACY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cAccuracy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_ALL_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long cAllValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_START_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date cStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_EQ_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cEqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_CALIB_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cCalibNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_FOR_ARRANGE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cForArrange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_EQ_TYPE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cEqType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_ARRANGE_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cArrangeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_LAB
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cLab;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_ARCHIVE_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cArchiveNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_CHECK_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date cCheckDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_CHECK_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cCheckIntv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_CHECK_EXPIRAITION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Date cCheckExpiraition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_MAX_CAPACITY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private Long cMaxCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_ZICHAN_TYPE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cZichanType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_CESHIZU
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cCeshizu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_SITE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_PROD_AREA
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cProdArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_ERJI_INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cErjiInstGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_STATUS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_ARRANGE_INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cArrangeInstGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_EQ_NAME_EN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private String cEqNameEn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.NAME
     *
     * @return the value of INSTRUMENTS.NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.NAME
     *
     * @param name the value for INSTRUMENTS.NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.GROUP_NAME
     *
     * @return the value of INSTRUMENTS.GROUP_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.GROUP_NAME
     *
     * @param groupName the value for INSTRUMENTS.GROUP_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.DESCRIPTION
     *
     * @return the value of INSTRUMENTS.DESCRIPTION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.DESCRIPTION
     *
     * @param description the value for INSTRUMENTS.DESCRIPTION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.INST_GROUP
     *
     * @return the value of INSTRUMENTS.INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getInstGroup() {
        return instGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.INST_GROUP
     *
     * @param instGroup the value for INSTRUMENTS.INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setInstGroup(String instGroup) {
        this.instGroup = instGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.ON_LINE
     *
     * @return the value of INSTRUMENTS.ON_LINE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getOnLine() {
        return onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.ON_LINE
     *
     * @param onLine the value for INSTRUMENTS.ON_LINE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setOnLine(String onLine) {
        this.onLine = onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.LOCATION
     *
     * @return the value of INSTRUMENTS.LOCATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.LOCATION
     *
     * @param location the value for INSTRUMENTS.LOCATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.OPERATOR
     *
     * @return the value of INSTRUMENTS.OPERATOR
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.OPERATOR
     *
     * @param operator the value for INSTRUMENTS.OPERATOR
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.VENDOR
     *
     * @return the value of INSTRUMENTS.VENDOR
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.VENDOR
     *
     * @param vendor the value for INSTRUMENTS.VENDOR
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.SERIAL_NO
     *
     * @return the value of INSTRUMENTS.SERIAL_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.SERIAL_NO
     *
     * @param serialNo the value for INSTRUMENTS.SERIAL_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PM_DATE
     *
     * @return the value of INSTRUMENTS.PM_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getPmDate() {
        return pmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PM_DATE
     *
     * @param pmDate the value for INSTRUMENTS.PM_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPmDate(Date pmDate) {
        this.pmDate = pmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PM_INTV
     *
     * @return the value of INSTRUMENTS.PM_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getPmIntv() {
        return pmIntv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PM_INTV
     *
     * @param pmIntv the value for INSTRUMENTS.PM_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPmIntv(Long pmIntv) {
        this.pmIntv = pmIntv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PM_EXPIRATION
     *
     * @return the value of INSTRUMENTS.PM_EXPIRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getPmExpiration() {
        return pmExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PM_EXPIRATION
     *
     * @param pmExpiration the value for INSTRUMENTS.PM_EXPIRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPmExpiration(Date pmExpiration) {
        this.pmExpiration = pmExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.CALIB_DATE
     *
     * @return the value of INSTRUMENTS.CALIB_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getCalibDate() {
        return calibDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.CALIB_DATE
     *
     * @param calibDate the value for INSTRUMENTS.CALIB_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setCalibDate(Date calibDate) {
        this.calibDate = calibDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.CALIB_INTV
     *
     * @return the value of INSTRUMENTS.CALIB_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getCalibIntv() {
        return calibIntv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.CALIB_INTV
     *
     * @param calibIntv the value for INSTRUMENTS.CALIB_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setCalibIntv(Long calibIntv) {
        this.calibIntv = calibIntv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.CALIB_EXPIRATION
     *
     * @return the value of INSTRUMENTS.CALIB_EXPIRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getCalibExpiration() {
        return calibExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.CALIB_EXPIRATION
     *
     * @param calibExpiration the value for INSTRUMENTS.CALIB_EXPIRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setCalibExpiration(Date calibExpiration) {
        this.calibExpiration = calibExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.CHANGED_ON
     *
     * @return the value of INSTRUMENTS.CHANGED_ON
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getChangedOn() {
        return changedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.CHANGED_ON
     *
     * @param changedOn the value for INSTRUMENTS.CHANGED_ON
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setChangedOn(Date changedOn) {
        this.changedOn = changedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.CHANGED_BY
     *
     * @return the value of INSTRUMENTS.CHANGED_BY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.CHANGED_BY
     *
     * @param changedBy the value for INSTRUMENTS.CHANGED_BY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.REMOVED
     *
     * @return the value of INSTRUMENTS.REMOVED
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getRemoved() {
        return removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.REMOVED
     *
     * @param removed the value for INSTRUMENTS.REMOVED
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setRemoved(String removed) {
        this.removed = removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.EXT_LINK
     *
     * @return the value of INSTRUMENTS.EXT_LINK
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getExtLink() {
        return extLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.EXT_LINK
     *
     * @param extLink the value for INSTRUMENTS.EXT_LINK
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setExtLink(String extLink) {
        this.extLink = extLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.LINK_LOCATION
     *
     * @return the value of INSTRUMENTS.LINK_LOCATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getLinkLocation() {
        return linkLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.LINK_LOCATION
     *
     * @param linkLocation the value for INSTRUMENTS.LINK_LOCATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setLinkLocation(String linkLocation) {
        this.linkLocation = linkLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PARAMETER_1_NAME
     *
     * @return the value of INSTRUMENTS.PARAMETER_1_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getParameter1Name() {
        return parameter1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PARAMETER_1_NAME
     *
     * @param parameter1Name the value for INSTRUMENTS.PARAMETER_1_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setParameter1Name(String parameter1Name) {
        this.parameter1Name = parameter1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PARAMETER_1_VALUE
     *
     * @return the value of INSTRUMENTS.PARAMETER_1_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getParameter1Value() {
        return parameter1Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PARAMETER_1_VALUE
     *
     * @param parameter1Value the value for INSTRUMENTS.PARAMETER_1_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setParameter1Value(String parameter1Value) {
        this.parameter1Value = parameter1Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PARAMETER_2_NAME
     *
     * @return the value of INSTRUMENTS.PARAMETER_2_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getParameter2Name() {
        return parameter2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PARAMETER_2_NAME
     *
     * @param parameter2Name the value for INSTRUMENTS.PARAMETER_2_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setParameter2Name(String parameter2Name) {
        this.parameter2Name = parameter2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PARAMETER_2_VALUE
     *
     * @return the value of INSTRUMENTS.PARAMETER_2_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getParameter2Value() {
        return parameter2Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PARAMETER_2_VALUE
     *
     * @param parameter2Value the value for INSTRUMENTS.PARAMETER_2_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setParameter2Value(String parameter2Value) {
        this.parameter2Value = parameter2Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.LABSTATION
     *
     * @return the value of INSTRUMENTS.LABSTATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getLabstation() {
        return labstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.LABSTATION
     *
     * @param labstation the value for INSTRUMENTS.LABSTATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setLabstation(String labstation) {
        this.labstation = labstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.BAUD
     *
     * @return the value of INSTRUMENTS.BAUD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getBaud() {
        return baud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.BAUD
     *
     * @param baud the value for INSTRUMENTS.BAUD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setBaud(String baud) {
        this.baud = baud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PARITY
     *
     * @return the value of INSTRUMENTS.PARITY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getParity() {
        return parity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PARITY
     *
     * @param parity the value for INSTRUMENTS.PARITY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setParity(String parity) {
        this.parity = parity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.STOP_BITS
     *
     * @return the value of INSTRUMENTS.STOP_BITS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getStopBits() {
        return stopBits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.STOP_BITS
     *
     * @param stopBits the value for INSTRUMENTS.STOP_BITS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setStopBits(String stopBits) {
        this.stopBits = stopBits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.DATA_BITS
     *
     * @return the value of INSTRUMENTS.DATA_BITS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getDataBits() {
        return dataBits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.DATA_BITS
     *
     * @param dataBits the value for INSTRUMENTS.DATA_BITS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setDataBits(String dataBits) {
        this.dataBits = dataBits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.FLOW_CONTROL
     *
     * @return the value of INSTRUMENTS.FLOW_CONTROL
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getFlowControl() {
        return flowControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.FLOW_CONTROL
     *
     * @param flowControl the value for INSTRUMENTS.FLOW_CONTROL
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setFlowControl(String flowControl) {
        this.flowControl = flowControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.INSTRUMENT_CLASS
     *
     * @return the value of INSTRUMENTS.INSTRUMENT_CLASS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getInstrumentClass() {
        return instrumentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.INSTRUMENT_CLASS
     *
     * @param instrumentClass the value for INSTRUMENTS.INSTRUMENT_CLASS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setInstrumentClass(String instrumentClass) {
        this.instrumentClass = instrumentClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.LOW_THRESHOLD
     *
     * @return the value of INSTRUMENTS.LOW_THRESHOLD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public BigDecimal getLowThreshold() {
        return lowThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.LOW_THRESHOLD
     *
     * @param lowThreshold the value for INSTRUMENTS.LOW_THRESHOLD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setLowThreshold(BigDecimal lowThreshold) {
        this.lowThreshold = lowThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.HIGH_THRESHOLD
     *
     * @return the value of INSTRUMENTS.HIGH_THRESHOLD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public BigDecimal getHighThreshold() {
        return highThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.HIGH_THRESHOLD
     *
     * @param highThreshold the value for INSTRUMENTS.HIGH_THRESHOLD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setHighThreshold(BigDecimal highThreshold) {
        this.highThreshold = highThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.STABILITY_DELTA
     *
     * @return the value of INSTRUMENTS.STABILITY_DELTA
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public BigDecimal getStabilityDelta() {
        return stabilityDelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.STABILITY_DELTA
     *
     * @param stabilityDelta the value for INSTRUMENTS.STABILITY_DELTA
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setStabilityDelta(BigDecimal stabilityDelta) {
        this.stabilityDelta = stabilityDelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.STABILITY_NUMBER
     *
     * @return the value of INSTRUMENTS.STABILITY_NUMBER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getStabilityNumber() {
        return stabilityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.STABILITY_NUMBER
     *
     * @param stabilityNumber the value for INSTRUMENTS.STABILITY_NUMBER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setStabilityNumber(Long stabilityNumber) {
        this.stabilityNumber = stabilityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PARENT_INSTRUMENT
     *
     * @return the value of INSTRUMENTS.PARENT_INSTRUMENT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getParentInstrument() {
        return parentInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PARENT_INSTRUMENT
     *
     * @param parentInstrument the value for INSTRUMENTS.PARENT_INSTRUMENT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setParentInstrument(String parentInstrument) {
        this.parentInstrument = parentInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.INST_TEMPLATE
     *
     * @return the value of INSTRUMENTS.INST_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getInstTemplate() {
        return instTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.INST_TEMPLATE
     *
     * @param instTemplate the value for INSTRUMENTS.INST_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setInstTemplate(String instTemplate) {
        this.instTemplate = instTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.CALIB_TEMPLATE
     *
     * @return the value of INSTRUMENTS.CALIB_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getCalibTemplate() {
        return calibTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.CALIB_TEMPLATE
     *
     * @param calibTemplate the value for INSTRUMENTS.CALIB_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setCalibTemplate(String calibTemplate) {
        this.calibTemplate = calibTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PM_TEMPLATE
     *
     * @return the value of INSTRUMENTS.PM_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getPmTemplate() {
        return pmTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PM_TEMPLATE
     *
     * @param pmTemplate the value for INSTRUMENTS.PM_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPmTemplate(String pmTemplate) {
        this.pmTemplate = pmTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.SERVICE_TEMPLATE
     *
     * @return the value of INSTRUMENTS.SERVICE_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getServiceTemplate() {
        return serviceTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.SERVICE_TEMPLATE
     *
     * @param serviceTemplate the value for INSTRUMENTS.SERVICE_TEMPLATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setServiceTemplate(String serviceTemplate) {
        this.serviceTemplate = serviceTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.NEEDS_CALIBRATION
     *
     * @return the value of INSTRUMENTS.NEEDS_CALIBRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getNeedsCalibration() {
        return needsCalibration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.NEEDS_CALIBRATION
     *
     * @param needsCalibration the value for INSTRUMENTS.NEEDS_CALIBRATION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setNeedsCalibration(String needsCalibration) {
        this.needsCalibration = needsCalibration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.NEEDS_PM
     *
     * @return the value of INSTRUMENTS.NEEDS_PM
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getNeedsPm() {
        return needsPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.NEEDS_PM
     *
     * @param needsPm the value for INSTRUMENTS.NEEDS_PM
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setNeedsPm(String needsPm) {
        this.needsPm = needsPm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.IP_ADDRESS
     *
     * @return the value of INSTRUMENTS.IP_ADDRESS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.IP_ADDRESS
     *
     * @param ipAddress the value for INSTRUMENTS.IP_ADDRESS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PORT_NUMBER
     *
     * @return the value of INSTRUMENTS.PORT_NUMBER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getPortNumber() {
        return portNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PORT_NUMBER
     *
     * @param portNumber the value for INSTRUMENTS.PORT_NUMBER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPortNumber(Long portNumber) {
        this.portNumber = portNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.TERM_PATTERN
     *
     * @return the value of INSTRUMENTS.TERM_PATTERN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getTermPattern() {
        return termPattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.TERM_PATTERN
     *
     * @param termPattern the value for INSTRUMENTS.TERM_PATTERN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setTermPattern(String termPattern) {
        this.termPattern = termPattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.TIME_OUT
     *
     * @return the value of INSTRUMENTS.TIME_OUT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.TIME_OUT
     *
     * @param timeOut the value for INSTRUMENTS.TIME_OUT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setTimeOut(Long timeOut) {
        this.timeOut = timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.XMIT_PREFIX
     *
     * @return the value of INSTRUMENTS.XMIT_PREFIX
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getXmitPrefix() {
        return xmitPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.XMIT_PREFIX
     *
     * @param xmitPrefix the value for INSTRUMENTS.XMIT_PREFIX
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setXmitPrefix(String xmitPrefix) {
        this.xmitPrefix = xmitPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.XMIT_SUFFIX
     *
     * @return the value of INSTRUMENTS.XMIT_SUFFIX
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getXmitSuffix() {
        return xmitSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.XMIT_SUFFIX
     *
     * @param xmitSuffix the value for INSTRUMENTS.XMIT_SUFFIX
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setXmitSuffix(String xmitSuffix) {
        this.xmitSuffix = xmitSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.POLLING_TIME
     *
     * @return the value of INSTRUMENTS.POLLING_TIME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getPollingTime() {
        return pollingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.POLLING_TIME
     *
     * @param pollingTime the value for INSTRUMENTS.POLLING_TIME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPollingTime(Long pollingTime) {
        this.pollingTime = pollingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.COMM_PORT
     *
     * @return the value of INSTRUMENTS.COMM_PORT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getCommPort() {
        return commPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.COMM_PORT
     *
     * @param commPort the value for INSTRUMENTS.COMM_PORT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setCommPort(String commPort) {
        this.commPort = commPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.HOLDS_SAMPLES
     *
     * @return the value of INSTRUMENTS.HOLDS_SAMPLES
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getHoldsSamples() {
        return holdsSamples;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.HOLDS_SAMPLES
     *
     * @param holdsSamples the value for INSTRUMENTS.HOLDS_SAMPLES
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setHoldsSamples(String holdsSamples) {
        this.holdsSamples = holdsSamples;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.DATA_PATH
     *
     * @return the value of INSTRUMENTS.DATA_PATH
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getDataPath() {
        return dataPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.DATA_PATH
     *
     * @param dataPath the value for INSTRUMENTS.DATA_PATH
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setDataPath(String dataPath) {
        this.dataPath = dataPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.DISCARD_TIME
     *
     * @return the value of INSTRUMENTS.DISCARD_TIME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getDiscardTime() {
        return discardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.DISCARD_TIME
     *
     * @param discardTime the value for INSTRUMENTS.DISCARD_TIME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setDiscardTime(Long discardTime) {
        this.discardTime = discardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.FILTER_SCRIPT
     *
     * @return the value of INSTRUMENTS.FILTER_SCRIPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getFilterScript() {
        return filterScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.FILTER_SCRIPT
     *
     * @param filterScript the value for INSTRUMENTS.FILTER_SCRIPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setFilterScript(String filterScript) {
        this.filterScript = filterScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PARSING_SCRIPT
     *
     * @return the value of INSTRUMENTS.PARSING_SCRIPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getParsingScript() {
        return parsingScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PARSING_SCRIPT
     *
     * @param parsingScript the value for INSTRUMENTS.PARSING_SCRIPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setParsingScript(String parsingScript) {
        this.parsingScript = parsingScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.POST_ARCHIVE_ACTION
     *
     * @return the value of INSTRUMENTS.POST_ARCHIVE_ACTION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getPostArchiveAction() {
        return postArchiveAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.POST_ARCHIVE_ACTION
     *
     * @param postArchiveAction the value for INSTRUMENTS.POST_ARCHIVE_ACTION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPostArchiveAction(String postArchiveAction) {
        this.postArchiveAction = postArchiveAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.SIZE_LIMIT
     *
     * @return the value of INSTRUMENTS.SIZE_LIMIT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getSizeLimit() {
        return sizeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.SIZE_LIMIT
     *
     * @param sizeLimit the value for INSTRUMENTS.SIZE_LIMIT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setSizeLimit(Long sizeLimit) {
        this.sizeLimit = sizeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.SYNC_PATTERN
     *
     * @return the value of INSTRUMENTS.SYNC_PATTERN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getSyncPattern() {
        return syncPattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.SYNC_PATTERN
     *
     * @param syncPattern the value for INSTRUMENTS.SYNC_PATTERN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setSyncPattern(String syncPattern) {
        this.syncPattern = syncPattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.RENAME_EXT
     *
     * @return the value of INSTRUMENTS.RENAME_EXT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getRenameExt() {
        return renameExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.RENAME_EXT
     *
     * @param renameExt the value for INSTRUMENTS.RENAME_EXT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setRenameExt(String renameExt) {
        this.renameExt = renameExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.SOURCE
     *
     * @return the value of INSTRUMENTS.SOURCE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.SOURCE
     *
     * @param source the value for INSTRUMENTS.SOURCE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.STEP
     *
     * @return the value of INSTRUMENTS.STEP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.STEP
     *
     * @param step the value for INSTRUMENTS.STEP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setStep(String step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.INCLUDE_SUBDIRS
     *
     * @return the value of INSTRUMENTS.INCLUDE_SUBDIRS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getIncludeSubdirs() {
        return includeSubdirs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.INCLUDE_SUBDIRS
     *
     * @param includeSubdirs the value for INSTRUMENTS.INCLUDE_SUBDIRS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setIncludeSubdirs(String includeSubdirs) {
        this.includeSubdirs = includeSubdirs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.FTP_USER
     *
     * @return the value of INSTRUMENTS.FTP_USER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getFtpUser() {
        return ftpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.FTP_USER
     *
     * @param ftpUser the value for INSTRUMENTS.FTP_USER
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setFtpUser(String ftpUser) {
        this.ftpUser = ftpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.DEBUG
     *
     * @return the value of INSTRUMENTS.DEBUG
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getDebug() {
        return debug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.DEBUG
     *
     * @param debug the value for INSTRUMENTS.DEBUG
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setDebug(String debug) {
        this.debug = debug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.DIRECTORY
     *
     * @return the value of INSTRUMENTS.DIRECTORY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getDirectory() {
        return directory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.DIRECTORY
     *
     * @param directory the value for INSTRUMENTS.DIRECTORY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setDirectory(String directory) {
        this.directory = directory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.FTP_MODE
     *
     * @return the value of INSTRUMENTS.FTP_MODE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getFtpMode() {
        return ftpMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.FTP_MODE
     *
     * @param ftpMode the value for INSTRUMENTS.FTP_MODE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setFtpMode(String ftpMode) {
        this.ftpMode = ftpMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.PASSWORD
     *
     * @return the value of INSTRUMENTS.PASSWORD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.PASSWORD
     *
     * @param password the value for INSTRUMENTS.PASSWORD
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.STORE_IN_DB_FILE
     *
     * @return the value of INSTRUMENTS.STORE_IN_DB_FILE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getStoreInDbFile() {
        return storeInDbFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.STORE_IN_DB_FILE
     *
     * @param storeInDbFile the value for INSTRUMENTS.STORE_IN_DB_FILE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setStoreInDbFile(String storeInDbFile) {
        this.storeInDbFile = storeInDbFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.DB_FILE_PROMPT
     *
     * @return the value of INSTRUMENTS.DB_FILE_PROMPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getDbFilePrompt() {
        return dbFilePrompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.DB_FILE_PROMPT
     *
     * @param dbFilePrompt the value for INSTRUMENTS.DB_FILE_PROMPT
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setDbFilePrompt(String dbFilePrompt) {
        this.dbFilePrompt = dbFilePrompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_EQ_NAME
     *
     * @return the value of INSTRUMENTS.C_EQ_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcEqName() {
        return cEqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_EQ_NAME
     *
     * @param cEqName the value for INSTRUMENTS.C_EQ_NAME
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcEqName(String cEqName) {
        this.cEqName = cEqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_MODEL
     *
     * @return the value of INSTRUMENTS.C_MODEL
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcModel() {
        return cModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_MODEL
     *
     * @param cModel the value for INSTRUMENTS.C_MODEL
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcModel(String cModel) {
        this.cModel = cModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_TECH_SPEC
     *
     * @return the value of INSTRUMENTS.C_TECH_SPEC
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcTechSpec() {
        return cTechSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_TECH_SPEC
     *
     * @param cTechSpec the value for INSTRUMENTS.C_TECH_SPEC
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcTechSpec(String cTechSpec) {
        this.cTechSpec = cTechSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_ACCURACY
     *
     * @return the value of INSTRUMENTS.C_ACCURACY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcAccuracy() {
        return cAccuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_ACCURACY
     *
     * @param cAccuracy the value for INSTRUMENTS.C_ACCURACY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcAccuracy(String cAccuracy) {
        this.cAccuracy = cAccuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_ALL_VALUE
     *
     * @return the value of INSTRUMENTS.C_ALL_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getcAllValue() {
        return cAllValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_ALL_VALUE
     *
     * @param cAllValue the value for INSTRUMENTS.C_ALL_VALUE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcAllValue(Long cAllValue) {
        this.cAllValue = cAllValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_START_DATE
     *
     * @return the value of INSTRUMENTS.C_START_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getcStartDate() {
        return cStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_START_DATE
     *
     * @param cStartDate the value for INSTRUMENTS.C_START_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcStartDate(Date cStartDate) {
        this.cStartDate = cStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_EQ_NO
     *
     * @return the value of INSTRUMENTS.C_EQ_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcEqNo() {
        return cEqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_EQ_NO
     *
     * @param cEqNo the value for INSTRUMENTS.C_EQ_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcEqNo(String cEqNo) {
        this.cEqNo = cEqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_CALIB_NO
     *
     * @return the value of INSTRUMENTS.C_CALIB_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcCalibNo() {
        return cCalibNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_CALIB_NO
     *
     * @param cCalibNo the value for INSTRUMENTS.C_CALIB_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcCalibNo(String cCalibNo) {
        this.cCalibNo = cCalibNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_FOR_ARRANGE
     *
     * @return the value of INSTRUMENTS.C_FOR_ARRANGE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcForArrange() {
        return cForArrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_FOR_ARRANGE
     *
     * @param cForArrange the value for INSTRUMENTS.C_FOR_ARRANGE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcForArrange(String cForArrange) {
        this.cForArrange = cForArrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_EQ_TYPE
     *
     * @return the value of INSTRUMENTS.C_EQ_TYPE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcEqType() {
        return cEqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_EQ_TYPE
     *
     * @param cEqType the value for INSTRUMENTS.C_EQ_TYPE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcEqType(String cEqType) {
        this.cEqType = cEqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_ARRANGE_NO
     *
     * @return the value of INSTRUMENTS.C_ARRANGE_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcArrangeNo() {
        return cArrangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_ARRANGE_NO
     *
     * @param cArrangeNo the value for INSTRUMENTS.C_ARRANGE_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcArrangeNo(String cArrangeNo) {
        this.cArrangeNo = cArrangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_LAB
     *
     * @return the value of INSTRUMENTS.C_LAB
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcLab() {
        return cLab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_LAB
     *
     * @param cLab the value for INSTRUMENTS.C_LAB
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcLab(String cLab) {
        this.cLab = cLab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_ARCHIVE_NO
     *
     * @return the value of INSTRUMENTS.C_ARCHIVE_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcArchiveNo() {
        return cArchiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_ARCHIVE_NO
     *
     * @param cArchiveNo the value for INSTRUMENTS.C_ARCHIVE_NO
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcArchiveNo(String cArchiveNo) {
        this.cArchiveNo = cArchiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_CHECK_DATE
     *
     * @return the value of INSTRUMENTS.C_CHECK_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getcCheckDate() {
        return cCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_CHECK_DATE
     *
     * @param cCheckDate the value for INSTRUMENTS.C_CHECK_DATE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcCheckDate(Date cCheckDate) {
        this.cCheckDate = cCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_CHECK_INTV
     *
     * @return the value of INSTRUMENTS.C_CHECK_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcCheckIntv() {
        return cCheckIntv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_CHECK_INTV
     *
     * @param cCheckIntv the value for INSTRUMENTS.C_CHECK_INTV
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcCheckIntv(String cCheckIntv) {
        this.cCheckIntv = cCheckIntv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_CHECK_EXPIRAITION
     *
     * @return the value of INSTRUMENTS.C_CHECK_EXPIRAITION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Date getcCheckExpiraition() {
        return cCheckExpiraition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_CHECK_EXPIRAITION
     *
     * @param cCheckExpiraition the value for INSTRUMENTS.C_CHECK_EXPIRAITION
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcCheckExpiraition(Date cCheckExpiraition) {
        this.cCheckExpiraition = cCheckExpiraition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_MAX_CAPACITY
     *
     * @return the value of INSTRUMENTS.C_MAX_CAPACITY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public Long getcMaxCapacity() {
        return cMaxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_MAX_CAPACITY
     *
     * @param cMaxCapacity the value for INSTRUMENTS.C_MAX_CAPACITY
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcMaxCapacity(Long cMaxCapacity) {
        this.cMaxCapacity = cMaxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_ZICHAN_TYPE
     *
     * @return the value of INSTRUMENTS.C_ZICHAN_TYPE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcZichanType() {
        return cZichanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_ZICHAN_TYPE
     *
     * @param cZichanType the value for INSTRUMENTS.C_ZICHAN_TYPE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcZichanType(String cZichanType) {
        this.cZichanType = cZichanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_CESHIZU
     *
     * @return the value of INSTRUMENTS.C_CESHIZU
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcCeshizu() {
        return cCeshizu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_CESHIZU
     *
     * @param cCeshizu the value for INSTRUMENTS.C_CESHIZU
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcCeshizu(String cCeshizu) {
        this.cCeshizu = cCeshizu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_SITE
     *
     * @return the value of INSTRUMENTS.C_SITE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcSite() {
        return cSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_SITE
     *
     * @param cSite the value for INSTRUMENTS.C_SITE
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcSite(String cSite) {
        this.cSite = cSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_PROD_AREA
     *
     * @return the value of INSTRUMENTS.C_PROD_AREA
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcProdArea() {
        return cProdArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_PROD_AREA
     *
     * @param cProdArea the value for INSTRUMENTS.C_PROD_AREA
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcProdArea(String cProdArea) {
        this.cProdArea = cProdArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_ERJI_INST_GROUP
     *
     * @return the value of INSTRUMENTS.C_ERJI_INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcErjiInstGroup() {
        return cErjiInstGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_ERJI_INST_GROUP
     *
     * @param cErjiInstGroup the value for INSTRUMENTS.C_ERJI_INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcErjiInstGroup(String cErjiInstGroup) {
        this.cErjiInstGroup = cErjiInstGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_STATUS
     *
     * @return the value of INSTRUMENTS.C_STATUS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcStatus() {
        return cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_STATUS
     *
     * @param cStatus the value for INSTRUMENTS.C_STATUS
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcStatus(String cStatus) {
        this.cStatus = cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_ARRANGE_INST_GROUP
     *
     * @return the value of INSTRUMENTS.C_ARRANGE_INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcArrangeInstGroup() {
        return cArrangeInstGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_ARRANGE_INST_GROUP
     *
     * @param cArrangeInstGroup the value for INSTRUMENTS.C_ARRANGE_INST_GROUP
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcArrangeInstGroup(String cArrangeInstGroup) {
        this.cArrangeInstGroup = cArrangeInstGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_EQ_NAME_EN
     *
     * @return the value of INSTRUMENTS.C_EQ_NAME_EN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public String getcEqNameEn() {
        return cEqNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_EQ_NAME_EN
     *
     * @param cEqNameEn the value for INSTRUMENTS.C_EQ_NAME_EN
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcEqNameEn(String cEqNameEn) {
        this.cEqNameEn = cEqNameEn;
    }
}