package cn.besbing.Entities;

public class InstrumentsWithBLOBs extends Instruments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_FILES1
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private byte[] cFiles1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_FILES2
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private byte[] cFiles2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_FILES3
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private byte[] cFiles3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_FILES4
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private byte[] cFiles4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTRUMENTS.C_FILES5
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    private byte[] cFiles5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_FILES1
     *
     * @return the value of INSTRUMENTS.C_FILES1
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public byte[] getcFiles1() {
        return cFiles1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_FILES1
     *
     * @param cFiles1 the value for INSTRUMENTS.C_FILES1
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcFiles1(byte[] cFiles1) {
        this.cFiles1 = cFiles1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_FILES2
     *
     * @return the value of INSTRUMENTS.C_FILES2
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public byte[] getcFiles2() {
        return cFiles2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_FILES2
     *
     * @param cFiles2 the value for INSTRUMENTS.C_FILES2
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcFiles2(byte[] cFiles2) {
        this.cFiles2 = cFiles2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_FILES3
     *
     * @return the value of INSTRUMENTS.C_FILES3
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public byte[] getcFiles3() {
        return cFiles3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_FILES3
     *
     * @param cFiles3 the value for INSTRUMENTS.C_FILES3
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcFiles3(byte[] cFiles3) {
        this.cFiles3 = cFiles3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_FILES4
     *
     * @return the value of INSTRUMENTS.C_FILES4
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public byte[] getcFiles4() {
        return cFiles4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_FILES4
     *
     * @param cFiles4 the value for INSTRUMENTS.C_FILES4
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcFiles4(byte[] cFiles4) {
        this.cFiles4 = cFiles4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTRUMENTS.C_FILES5
     *
     * @return the value of INSTRUMENTS.C_FILES5
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public byte[] getcFiles5() {
        return cFiles5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTRUMENTS.C_FILES5
     *
     * @param cFiles5 the value for INSTRUMENTS.C_FILES5
     *
     * @mbg.generated Wed Apr 29 17:55:31 CST 2020
     */
    public void setcFiles5(byte[] cFiles5) {
        this.cFiles5 = cFiles5;
    }
}