package cn.besbing.Entities;

import java.util.Date;

public class LimsUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.USER_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.FULL_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.GROUP_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.PHONE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.EMAIL_ADDR
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String emailAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LAB
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String lab;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.EXT_LINK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String extLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.DEFAULT_WORKFLOW
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String defaultWorkflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LANGUAGE_PREFIX
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String languagePrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.GMT_OFFSET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long gmtOffset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.DAYLIGHT_SAVINGS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String daylightSavings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.USES_ROLES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String usesRoles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.IS_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String isRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.USER_DISABLED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String userDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.DATE_DISABLED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Date dateDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long interval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.HOLIDAY_SCHEDULE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String holidaySchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.USE_CUSTOMER_TEMP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String useCustomerTemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SAMPLE_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String sampleConstraint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.TEST_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String testConstraint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.RESULT_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String resultConstraint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SAMPLE_DISP_FLDS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String sampleDispFlds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.TEST_DISP_FLDS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String testDispFlds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.OPEN_MSG_WINDOW
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String openMsgWindow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LDAP_UID
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String ldapUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LDAP_SERVER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String ldapServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SAMPLE_FILTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String sampleFilter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.BROWSE_FILTER_REQD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String browseFilterReqd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.TIMEOUT_INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long timeoutInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.CLOSE_LINK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String closeLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SIGNATURE_FILE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String signatureFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LOCK_ON_TIMEOUT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String lockOnTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LOCK_TIMEOUT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long lockTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.ALLOCATE_LICENSE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String allocateLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.RESTRICTED_USE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String restrictedUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SELF_SIGN_FILE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String selfSignFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.TOKEN_SERIAL_NO
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String tokenSerialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.DESCRIPTION
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.EXPIRES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Date expires;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String expired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SELF_SIGN_EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String selfSignExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.PSWD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String pswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.PROJECT_FILTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String projectFilter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.NOTEBOOK_REF_NUM
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long notebookRefNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String browseConfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.TEST_BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String testBrowseConfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.PROJ_BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String projBrowseConfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.CHANGED_ON
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Date changedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.CHANGED_BY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String changedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SIGNATURE_CHECK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String signatureCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.REMOVED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String removed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.USER_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SIGNING_PSWD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String signingPswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SIGNING_EXPIRES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Date signingExpires;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SIGNING_EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String signingExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SIGNING_INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long signingInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LICENSE_GROUP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String licenseGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.ADDRESS_BOOK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String addressBook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.WEB_REMEMBER_ME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String webRememberMe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.WEB_LABEL_PRINTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String webLabelPrinter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LAST_FAILED_LOGIN
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Date lastFailedLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LAST_FAILED_IP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String lastFailedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.FAILED_LOGINS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long failedLogins;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LAST_GOOD_LOGIN
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Date lastGoodLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LAST_GOOD_IP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String lastGoodIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.PAPER_SET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String paperSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.LOCATION
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.RECORD_SET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String recordSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.T_CUSTOMER_CONTACT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private Long tCustomerContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.T_DEF_RESULT_QRY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String tDefResultQry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.T_JOB_TITLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String tJobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.TRACK_CHANGES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String trackChanges;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.WEB_LABEL_PTR_PORT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String webLabelPtrPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.GROUP_NAME_FROM_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String groupNameFromRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.COMBINE_ROLES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String combineRoles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.ENABLE_BREAKPOINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String enableBreakpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.ENABLE_TRACE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String enableTrace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.SSO_UID
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String ssoUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.C_COMPANY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String cCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.C_DEPARTMENT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String cDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.C_IS_QA
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String cIsQa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIMS_USERS.C_APPROVAL_ROUTING
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    private String cApprovalRouting;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.USER_NAME
     *
     * @return the value of LIMS_USERS.USER_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.USER_NAME
     *
     * @param userName the value for LIMS_USERS.USER_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.FULL_NAME
     *
     * @return the value of LIMS_USERS.FULL_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.FULL_NAME
     *
     * @param fullName the value for LIMS_USERS.FULL_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.GROUP_NAME
     *
     * @return the value of LIMS_USERS.GROUP_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.GROUP_NAME
     *
     * @param groupName the value for LIMS_USERS.GROUP_NAME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.PHONE
     *
     * @return the value of LIMS_USERS.PHONE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.PHONE
     *
     * @param phone the value for LIMS_USERS.PHONE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.EMAIL_ADDR
     *
     * @return the value of LIMS_USERS.EMAIL_ADDR
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.EMAIL_ADDR
     *
     * @param emailAddr the value for LIMS_USERS.EMAIL_ADDR
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LAB
     *
     * @return the value of LIMS_USERS.LAB
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLab() {
        return lab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LAB
     *
     * @param lab the value for LIMS_USERS.LAB
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLab(String lab) {
        this.lab = lab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.EXT_LINK
     *
     * @return the value of LIMS_USERS.EXT_LINK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getExtLink() {
        return extLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.EXT_LINK
     *
     * @param extLink the value for LIMS_USERS.EXT_LINK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setExtLink(String extLink) {
        this.extLink = extLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.DEFAULT_WORKFLOW
     *
     * @return the value of LIMS_USERS.DEFAULT_WORKFLOW
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getDefaultWorkflow() {
        return defaultWorkflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.DEFAULT_WORKFLOW
     *
     * @param defaultWorkflow the value for LIMS_USERS.DEFAULT_WORKFLOW
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setDefaultWorkflow(String defaultWorkflow) {
        this.defaultWorkflow = defaultWorkflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LANGUAGE_PREFIX
     *
     * @return the value of LIMS_USERS.LANGUAGE_PREFIX
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLanguagePrefix() {
        return languagePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LANGUAGE_PREFIX
     *
     * @param languagePrefix the value for LIMS_USERS.LANGUAGE_PREFIX
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLanguagePrefix(String languagePrefix) {
        this.languagePrefix = languagePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.GMT_OFFSET
     *
     * @return the value of LIMS_USERS.GMT_OFFSET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long getGmtOffset() {
        return gmtOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.GMT_OFFSET
     *
     * @param gmtOffset the value for LIMS_USERS.GMT_OFFSET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setGmtOffset(Long gmtOffset) {
        this.gmtOffset = gmtOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.DAYLIGHT_SAVINGS
     *
     * @return the value of LIMS_USERS.DAYLIGHT_SAVINGS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getDaylightSavings() {
        return daylightSavings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.DAYLIGHT_SAVINGS
     *
     * @param daylightSavings the value for LIMS_USERS.DAYLIGHT_SAVINGS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setDaylightSavings(String daylightSavings) {
        this.daylightSavings = daylightSavings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.USES_ROLES
     *
     * @return the value of LIMS_USERS.USES_ROLES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getUsesRoles() {
        return usesRoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.USES_ROLES
     *
     * @param usesRoles the value for LIMS_USERS.USES_ROLES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setUsesRoles(String usesRoles) {
        this.usesRoles = usesRoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.IS_ROLE
     *
     * @return the value of LIMS_USERS.IS_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getIsRole() {
        return isRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.IS_ROLE
     *
     * @param isRole the value for LIMS_USERS.IS_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setIsRole(String isRole) {
        this.isRole = isRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.USER_DISABLED
     *
     * @return the value of LIMS_USERS.USER_DISABLED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getUserDisabled() {
        return userDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.USER_DISABLED
     *
     * @param userDisabled the value for LIMS_USERS.USER_DISABLED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setUserDisabled(String userDisabled) {
        this.userDisabled = userDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.DATE_DISABLED
     *
     * @return the value of LIMS_USERS.DATE_DISABLED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Date getDateDisabled() {
        return dateDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.DATE_DISABLED
     *
     * @param dateDisabled the value for LIMS_USERS.DATE_DISABLED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setDateDisabled(Date dateDisabled) {
        this.dateDisabled = dateDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.INTERVAL
     *
     * @return the value of LIMS_USERS.INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long getInterval() {
        return interval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.INTERVAL
     *
     * @param interval the value for LIMS_USERS.INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setInterval(Long interval) {
        this.interval = interval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.HOLIDAY_SCHEDULE
     *
     * @return the value of LIMS_USERS.HOLIDAY_SCHEDULE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getHolidaySchedule() {
        return holidaySchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.HOLIDAY_SCHEDULE
     *
     * @param holidaySchedule the value for LIMS_USERS.HOLIDAY_SCHEDULE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setHolidaySchedule(String holidaySchedule) {
        this.holidaySchedule = holidaySchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.USE_CUSTOMER_TEMP
     *
     * @return the value of LIMS_USERS.USE_CUSTOMER_TEMP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getUseCustomerTemp() {
        return useCustomerTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.USE_CUSTOMER_TEMP
     *
     * @param useCustomerTemp the value for LIMS_USERS.USE_CUSTOMER_TEMP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setUseCustomerTemp(String useCustomerTemp) {
        this.useCustomerTemp = useCustomerTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SAMPLE_CONSTRAINT
     *
     * @return the value of LIMS_USERS.SAMPLE_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSampleConstraint() {
        return sampleConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SAMPLE_CONSTRAINT
     *
     * @param sampleConstraint the value for LIMS_USERS.SAMPLE_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSampleConstraint(String sampleConstraint) {
        this.sampleConstraint = sampleConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.TEST_CONSTRAINT
     *
     * @return the value of LIMS_USERS.TEST_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getTestConstraint() {
        return testConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.TEST_CONSTRAINT
     *
     * @param testConstraint the value for LIMS_USERS.TEST_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setTestConstraint(String testConstraint) {
        this.testConstraint = testConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.RESULT_CONSTRAINT
     *
     * @return the value of LIMS_USERS.RESULT_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getResultConstraint() {
        return resultConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.RESULT_CONSTRAINT
     *
     * @param resultConstraint the value for LIMS_USERS.RESULT_CONSTRAINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setResultConstraint(String resultConstraint) {
        this.resultConstraint = resultConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SAMPLE_DISP_FLDS
     *
     * @return the value of LIMS_USERS.SAMPLE_DISP_FLDS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSampleDispFlds() {
        return sampleDispFlds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SAMPLE_DISP_FLDS
     *
     * @param sampleDispFlds the value for LIMS_USERS.SAMPLE_DISP_FLDS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSampleDispFlds(String sampleDispFlds) {
        this.sampleDispFlds = sampleDispFlds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.TEST_DISP_FLDS
     *
     * @return the value of LIMS_USERS.TEST_DISP_FLDS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getTestDispFlds() {
        return testDispFlds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.TEST_DISP_FLDS
     *
     * @param testDispFlds the value for LIMS_USERS.TEST_DISP_FLDS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setTestDispFlds(String testDispFlds) {
        this.testDispFlds = testDispFlds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.OPEN_MSG_WINDOW
     *
     * @return the value of LIMS_USERS.OPEN_MSG_WINDOW
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getOpenMsgWindow() {
        return openMsgWindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.OPEN_MSG_WINDOW
     *
     * @param openMsgWindow the value for LIMS_USERS.OPEN_MSG_WINDOW
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setOpenMsgWindow(String openMsgWindow) {
        this.openMsgWindow = openMsgWindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LDAP_UID
     *
     * @return the value of LIMS_USERS.LDAP_UID
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLdapUid() {
        return ldapUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LDAP_UID
     *
     * @param ldapUid the value for LIMS_USERS.LDAP_UID
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLdapUid(String ldapUid) {
        this.ldapUid = ldapUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LDAP_SERVER
     *
     * @return the value of LIMS_USERS.LDAP_SERVER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLdapServer() {
        return ldapServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LDAP_SERVER
     *
     * @param ldapServer the value for LIMS_USERS.LDAP_SERVER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLdapServer(String ldapServer) {
        this.ldapServer = ldapServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SAMPLE_FILTER
     *
     * @return the value of LIMS_USERS.SAMPLE_FILTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSampleFilter() {
        return sampleFilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SAMPLE_FILTER
     *
     * @param sampleFilter the value for LIMS_USERS.SAMPLE_FILTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSampleFilter(String sampleFilter) {
        this.sampleFilter = sampleFilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.BROWSE_FILTER_REQD
     *
     * @return the value of LIMS_USERS.BROWSE_FILTER_REQD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getBrowseFilterReqd() {
        return browseFilterReqd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.BROWSE_FILTER_REQD
     *
     * @param browseFilterReqd the value for LIMS_USERS.BROWSE_FILTER_REQD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setBrowseFilterReqd(String browseFilterReqd) {
        this.browseFilterReqd = browseFilterReqd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.TIMEOUT_INTERVAL
     *
     * @return the value of LIMS_USERS.TIMEOUT_INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long getTimeoutInterval() {
        return timeoutInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.TIMEOUT_INTERVAL
     *
     * @param timeoutInterval the value for LIMS_USERS.TIMEOUT_INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setTimeoutInterval(Long timeoutInterval) {
        this.timeoutInterval = timeoutInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.CLOSE_LINK
     *
     * @return the value of LIMS_USERS.CLOSE_LINK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getCloseLink() {
        return closeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.CLOSE_LINK
     *
     * @param closeLink the value for LIMS_USERS.CLOSE_LINK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setCloseLink(String closeLink) {
        this.closeLink = closeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SIGNATURE_FILE
     *
     * @return the value of LIMS_USERS.SIGNATURE_FILE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSignatureFile() {
        return signatureFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SIGNATURE_FILE
     *
     * @param signatureFile the value for LIMS_USERS.SIGNATURE_FILE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSignatureFile(String signatureFile) {
        this.signatureFile = signatureFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LOCK_ON_TIMEOUT
     *
     * @return the value of LIMS_USERS.LOCK_ON_TIMEOUT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLockOnTimeout() {
        return lockOnTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LOCK_ON_TIMEOUT
     *
     * @param lockOnTimeout the value for LIMS_USERS.LOCK_ON_TIMEOUT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLockOnTimeout(String lockOnTimeout) {
        this.lockOnTimeout = lockOnTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LOCK_TIMEOUT
     *
     * @return the value of LIMS_USERS.LOCK_TIMEOUT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long getLockTimeout() {
        return lockTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LOCK_TIMEOUT
     *
     * @param lockTimeout the value for LIMS_USERS.LOCK_TIMEOUT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLockTimeout(Long lockTimeout) {
        this.lockTimeout = lockTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.ALLOCATE_LICENSE
     *
     * @return the value of LIMS_USERS.ALLOCATE_LICENSE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getAllocateLicense() {
        return allocateLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.ALLOCATE_LICENSE
     *
     * @param allocateLicense the value for LIMS_USERS.ALLOCATE_LICENSE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setAllocateLicense(String allocateLicense) {
        this.allocateLicense = allocateLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.RESTRICTED_USE
     *
     * @return the value of LIMS_USERS.RESTRICTED_USE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getRestrictedUse() {
        return restrictedUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.RESTRICTED_USE
     *
     * @param restrictedUse the value for LIMS_USERS.RESTRICTED_USE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setRestrictedUse(String restrictedUse) {
        this.restrictedUse = restrictedUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SELF_SIGN_FILE
     *
     * @return the value of LIMS_USERS.SELF_SIGN_FILE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSelfSignFile() {
        return selfSignFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SELF_SIGN_FILE
     *
     * @param selfSignFile the value for LIMS_USERS.SELF_SIGN_FILE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSelfSignFile(String selfSignFile) {
        this.selfSignFile = selfSignFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.TOKEN_SERIAL_NO
     *
     * @return the value of LIMS_USERS.TOKEN_SERIAL_NO
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getTokenSerialNo() {
        return tokenSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.TOKEN_SERIAL_NO
     *
     * @param tokenSerialNo the value for LIMS_USERS.TOKEN_SERIAL_NO
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setTokenSerialNo(String tokenSerialNo) {
        this.tokenSerialNo = tokenSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.DESCRIPTION
     *
     * @return the value of LIMS_USERS.DESCRIPTION
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.DESCRIPTION
     *
     * @param description the value for LIMS_USERS.DESCRIPTION
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.EXPIRES
     *
     * @return the value of LIMS_USERS.EXPIRES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Date getExpires() {
        return expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.EXPIRES
     *
     * @param expires the value for LIMS_USERS.EXPIRES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setExpires(Date expires) {
        this.expires = expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.EXPIRED
     *
     * @return the value of LIMS_USERS.EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getExpired() {
        return expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.EXPIRED
     *
     * @param expired the value for LIMS_USERS.EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setExpired(String expired) {
        this.expired = expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SELF_SIGN_EXPIRED
     *
     * @return the value of LIMS_USERS.SELF_SIGN_EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSelfSignExpired() {
        return selfSignExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SELF_SIGN_EXPIRED
     *
     * @param selfSignExpired the value for LIMS_USERS.SELF_SIGN_EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSelfSignExpired(String selfSignExpired) {
        this.selfSignExpired = selfSignExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.PSWD
     *
     * @return the value of LIMS_USERS.PSWD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getPswd() {
        return pswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.PSWD
     *
     * @param pswd the value for LIMS_USERS.PSWD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setPswd(String pswd) {
        this.pswd = pswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.PROJECT_FILTER
     *
     * @return the value of LIMS_USERS.PROJECT_FILTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getProjectFilter() {
        return projectFilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.PROJECT_FILTER
     *
     * @param projectFilter the value for LIMS_USERS.PROJECT_FILTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setProjectFilter(String projectFilter) {
        this.projectFilter = projectFilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.NOTEBOOK_REF_NUM
     *
     * @return the value of LIMS_USERS.NOTEBOOK_REF_NUM
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long getNotebookRefNum() {
        return notebookRefNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.NOTEBOOK_REF_NUM
     *
     * @param notebookRefNum the value for LIMS_USERS.NOTEBOOK_REF_NUM
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setNotebookRefNum(Long notebookRefNum) {
        this.notebookRefNum = notebookRefNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.BROWSE_CONFIG
     *
     * @return the value of LIMS_USERS.BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getBrowseConfig() {
        return browseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.BROWSE_CONFIG
     *
     * @param browseConfig the value for LIMS_USERS.BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setBrowseConfig(String browseConfig) {
        this.browseConfig = browseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.TEST_BROWSE_CONFIG
     *
     * @return the value of LIMS_USERS.TEST_BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getTestBrowseConfig() {
        return testBrowseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.TEST_BROWSE_CONFIG
     *
     * @param testBrowseConfig the value for LIMS_USERS.TEST_BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setTestBrowseConfig(String testBrowseConfig) {
        this.testBrowseConfig = testBrowseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.PROJ_BROWSE_CONFIG
     *
     * @return the value of LIMS_USERS.PROJ_BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getProjBrowseConfig() {
        return projBrowseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.PROJ_BROWSE_CONFIG
     *
     * @param projBrowseConfig the value for LIMS_USERS.PROJ_BROWSE_CONFIG
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setProjBrowseConfig(String projBrowseConfig) {
        this.projBrowseConfig = projBrowseConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.CHANGED_ON
     *
     * @return the value of LIMS_USERS.CHANGED_ON
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Date getChangedOn() {
        return changedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.CHANGED_ON
     *
     * @param changedOn the value for LIMS_USERS.CHANGED_ON
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setChangedOn(Date changedOn) {
        this.changedOn = changedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.CHANGED_BY
     *
     * @return the value of LIMS_USERS.CHANGED_BY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getChangedBy() {
        return changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.CHANGED_BY
     *
     * @param changedBy the value for LIMS_USERS.CHANGED_BY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SIGNATURE_CHECK
     *
     * @return the value of LIMS_USERS.SIGNATURE_CHECK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSignatureCheck() {
        return signatureCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SIGNATURE_CHECK
     *
     * @param signatureCheck the value for LIMS_USERS.SIGNATURE_CHECK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSignatureCheck(String signatureCheck) {
        this.signatureCheck = signatureCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.REMOVED
     *
     * @return the value of LIMS_USERS.REMOVED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getRemoved() {
        return removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.REMOVED
     *
     * @param removed the value for LIMS_USERS.REMOVED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setRemoved(String removed) {
        this.removed = removed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.USER_ROLE
     *
     * @return the value of LIMS_USERS.USER_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.USER_ROLE
     *
     * @param userRole the value for LIMS_USERS.USER_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SIGNING_PSWD
     *
     * @return the value of LIMS_USERS.SIGNING_PSWD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSigningPswd() {
        return signingPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SIGNING_PSWD
     *
     * @param signingPswd the value for LIMS_USERS.SIGNING_PSWD
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSigningPswd(String signingPswd) {
        this.signingPswd = signingPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SIGNING_EXPIRES
     *
     * @return the value of LIMS_USERS.SIGNING_EXPIRES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Date getSigningExpires() {
        return signingExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SIGNING_EXPIRES
     *
     * @param signingExpires the value for LIMS_USERS.SIGNING_EXPIRES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSigningExpires(Date signingExpires) {
        this.signingExpires = signingExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SIGNING_EXPIRED
     *
     * @return the value of LIMS_USERS.SIGNING_EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSigningExpired() {
        return signingExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SIGNING_EXPIRED
     *
     * @param signingExpired the value for LIMS_USERS.SIGNING_EXPIRED
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSigningExpired(String signingExpired) {
        this.signingExpired = signingExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SIGNING_INTERVAL
     *
     * @return the value of LIMS_USERS.SIGNING_INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long getSigningInterval() {
        return signingInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SIGNING_INTERVAL
     *
     * @param signingInterval the value for LIMS_USERS.SIGNING_INTERVAL
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSigningInterval(Long signingInterval) {
        this.signingInterval = signingInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LICENSE_GROUP
     *
     * @return the value of LIMS_USERS.LICENSE_GROUP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLicenseGroup() {
        return licenseGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LICENSE_GROUP
     *
     * @param licenseGroup the value for LIMS_USERS.LICENSE_GROUP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLicenseGroup(String licenseGroup) {
        this.licenseGroup = licenseGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.ADDRESS_BOOK
     *
     * @return the value of LIMS_USERS.ADDRESS_BOOK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getAddressBook() {
        return addressBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.ADDRESS_BOOK
     *
     * @param addressBook the value for LIMS_USERS.ADDRESS_BOOK
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setAddressBook(String addressBook) {
        this.addressBook = addressBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.WEB_REMEMBER_ME
     *
     * @return the value of LIMS_USERS.WEB_REMEMBER_ME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getWebRememberMe() {
        return webRememberMe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.WEB_REMEMBER_ME
     *
     * @param webRememberMe the value for LIMS_USERS.WEB_REMEMBER_ME
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setWebRememberMe(String webRememberMe) {
        this.webRememberMe = webRememberMe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.WEB_LABEL_PRINTER
     *
     * @return the value of LIMS_USERS.WEB_LABEL_PRINTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getWebLabelPrinter() {
        return webLabelPrinter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.WEB_LABEL_PRINTER
     *
     * @param webLabelPrinter the value for LIMS_USERS.WEB_LABEL_PRINTER
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setWebLabelPrinter(String webLabelPrinter) {
        this.webLabelPrinter = webLabelPrinter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LAST_FAILED_LOGIN
     *
     * @return the value of LIMS_USERS.LAST_FAILED_LOGIN
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Date getLastFailedLogin() {
        return lastFailedLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LAST_FAILED_LOGIN
     *
     * @param lastFailedLogin the value for LIMS_USERS.LAST_FAILED_LOGIN
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLastFailedLogin(Date lastFailedLogin) {
        this.lastFailedLogin = lastFailedLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LAST_FAILED_IP
     *
     * @return the value of LIMS_USERS.LAST_FAILED_IP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLastFailedIp() {
        return lastFailedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LAST_FAILED_IP
     *
     * @param lastFailedIp the value for LIMS_USERS.LAST_FAILED_IP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLastFailedIp(String lastFailedIp) {
        this.lastFailedIp = lastFailedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.FAILED_LOGINS
     *
     * @return the value of LIMS_USERS.FAILED_LOGINS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long getFailedLogins() {
        return failedLogins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.FAILED_LOGINS
     *
     * @param failedLogins the value for LIMS_USERS.FAILED_LOGINS
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setFailedLogins(Long failedLogins) {
        this.failedLogins = failedLogins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LAST_GOOD_LOGIN
     *
     * @return the value of LIMS_USERS.LAST_GOOD_LOGIN
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Date getLastGoodLogin() {
        return lastGoodLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LAST_GOOD_LOGIN
     *
     * @param lastGoodLogin the value for LIMS_USERS.LAST_GOOD_LOGIN
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLastGoodLogin(Date lastGoodLogin) {
        this.lastGoodLogin = lastGoodLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LAST_GOOD_IP
     *
     * @return the value of LIMS_USERS.LAST_GOOD_IP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLastGoodIp() {
        return lastGoodIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LAST_GOOD_IP
     *
     * @param lastGoodIp the value for LIMS_USERS.LAST_GOOD_IP
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLastGoodIp(String lastGoodIp) {
        this.lastGoodIp = lastGoodIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.PAPER_SET
     *
     * @return the value of LIMS_USERS.PAPER_SET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getPaperSet() {
        return paperSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.PAPER_SET
     *
     * @param paperSet the value for LIMS_USERS.PAPER_SET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setPaperSet(String paperSet) {
        this.paperSet = paperSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.LOCATION
     *
     * @return the value of LIMS_USERS.LOCATION
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.LOCATION
     *
     * @param location the value for LIMS_USERS.LOCATION
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.RECORD_SET
     *
     * @return the value of LIMS_USERS.RECORD_SET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getRecordSet() {
        return recordSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.RECORD_SET
     *
     * @param recordSet the value for LIMS_USERS.RECORD_SET
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setRecordSet(String recordSet) {
        this.recordSet = recordSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.T_CUSTOMER_CONTACT
     *
     * @return the value of LIMS_USERS.T_CUSTOMER_CONTACT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public Long gettCustomerContact() {
        return tCustomerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.T_CUSTOMER_CONTACT
     *
     * @param tCustomerContact the value for LIMS_USERS.T_CUSTOMER_CONTACT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void settCustomerContact(Long tCustomerContact) {
        this.tCustomerContact = tCustomerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.T_DEF_RESULT_QRY
     *
     * @return the value of LIMS_USERS.T_DEF_RESULT_QRY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String gettDefResultQry() {
        return tDefResultQry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.T_DEF_RESULT_QRY
     *
     * @param tDefResultQry the value for LIMS_USERS.T_DEF_RESULT_QRY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void settDefResultQry(String tDefResultQry) {
        this.tDefResultQry = tDefResultQry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.T_JOB_TITLE
     *
     * @return the value of LIMS_USERS.T_JOB_TITLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String gettJobTitle() {
        return tJobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.T_JOB_TITLE
     *
     * @param tJobTitle the value for LIMS_USERS.T_JOB_TITLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void settJobTitle(String tJobTitle) {
        this.tJobTitle = tJobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.TRACK_CHANGES
     *
     * @return the value of LIMS_USERS.TRACK_CHANGES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getTrackChanges() {
        return trackChanges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.TRACK_CHANGES
     *
     * @param trackChanges the value for LIMS_USERS.TRACK_CHANGES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setTrackChanges(String trackChanges) {
        this.trackChanges = trackChanges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.WEB_LABEL_PTR_PORT
     *
     * @return the value of LIMS_USERS.WEB_LABEL_PTR_PORT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getWebLabelPtrPort() {
        return webLabelPtrPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.WEB_LABEL_PTR_PORT
     *
     * @param webLabelPtrPort the value for LIMS_USERS.WEB_LABEL_PTR_PORT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setWebLabelPtrPort(String webLabelPtrPort) {
        this.webLabelPtrPort = webLabelPtrPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.GROUP_NAME_FROM_ROLE
     *
     * @return the value of LIMS_USERS.GROUP_NAME_FROM_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getGroupNameFromRole() {
        return groupNameFromRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.GROUP_NAME_FROM_ROLE
     *
     * @param groupNameFromRole the value for LIMS_USERS.GROUP_NAME_FROM_ROLE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setGroupNameFromRole(String groupNameFromRole) {
        this.groupNameFromRole = groupNameFromRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.COMBINE_ROLES
     *
     * @return the value of LIMS_USERS.COMBINE_ROLES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getCombineRoles() {
        return combineRoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.COMBINE_ROLES
     *
     * @param combineRoles the value for LIMS_USERS.COMBINE_ROLES
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setCombineRoles(String combineRoles) {
        this.combineRoles = combineRoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.ENABLE_BREAKPOINT
     *
     * @return the value of LIMS_USERS.ENABLE_BREAKPOINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getEnableBreakpoint() {
        return enableBreakpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.ENABLE_BREAKPOINT
     *
     * @param enableBreakpoint the value for LIMS_USERS.ENABLE_BREAKPOINT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setEnableBreakpoint(String enableBreakpoint) {
        this.enableBreakpoint = enableBreakpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.ENABLE_TRACE
     *
     * @return the value of LIMS_USERS.ENABLE_TRACE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getEnableTrace() {
        return enableTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.ENABLE_TRACE
     *
     * @param enableTrace the value for LIMS_USERS.ENABLE_TRACE
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setEnableTrace(String enableTrace) {
        this.enableTrace = enableTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.SSO_UID
     *
     * @return the value of LIMS_USERS.SSO_UID
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getSsoUid() {
        return ssoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.SSO_UID
     *
     * @param ssoUid the value for LIMS_USERS.SSO_UID
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setSsoUid(String ssoUid) {
        this.ssoUid = ssoUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.C_COMPANY
     *
     * @return the value of LIMS_USERS.C_COMPANY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getcCompany() {
        return cCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.C_COMPANY
     *
     * @param cCompany the value for LIMS_USERS.C_COMPANY
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setcCompany(String cCompany) {
        this.cCompany = cCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.C_DEPARTMENT
     *
     * @return the value of LIMS_USERS.C_DEPARTMENT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getcDepartment() {
        return cDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.C_DEPARTMENT
     *
     * @param cDepartment the value for LIMS_USERS.C_DEPARTMENT
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setcDepartment(String cDepartment) {
        this.cDepartment = cDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.C_IS_QA
     *
     * @return the value of LIMS_USERS.C_IS_QA
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getcIsQa() {
        return cIsQa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.C_IS_QA
     *
     * @param cIsQa the value for LIMS_USERS.C_IS_QA
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setcIsQa(String cIsQa) {
        this.cIsQa = cIsQa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIMS_USERS.C_APPROVAL_ROUTING
     *
     * @return the value of LIMS_USERS.C_APPROVAL_ROUTING
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public String getcApprovalRouting() {
        return cApprovalRouting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIMS_USERS.C_APPROVAL_ROUTING
     *
     * @param cApprovalRouting the value for LIMS_USERS.C_APPROVAL_ROUTING
     *
     * @mbg.generated Sun Apr 12 16:59:29 CST 2020
     */
    public void setcApprovalRouting(String cApprovalRouting) {
        this.cApprovalRouting = cApprovalRouting;
    }
}